services:
  app:
    container_name: telegram-mini-app-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_DATABASE_HOST=db
      - APP_DATABASE_PORT=5432
      - APP_DATABASE_USER=${POSTGRES_USER}
      - APP_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - APP_DATABASE_NAME=${POSTGRES_DB}
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: ud_telegram_miniapp_test
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: